### ISSUE TITLE
스터디 참여시 필요할 룰 설정 관련 의견 수렴 

### ISSUE THREAD

**Issue by ghost** [openstack-kr/community-project-management#2]
대략적으로 아래와 같은 최소한의 룰이 필요 한것 같습니다. 
1. 최소한 스터디 참여시에 첫번째 오프라인 모임에는 꼭 참석 
2. 최초 스터디 시작시 회비 -> 1만원정도

**Comment by ianychoi** [comment]
1번
- 첫 번째 오프라인 참석이 어려우신 분들도 있으니 제가 메일로 한 번 더 물어보는 것도 괜찮지 싶습니다.
- 오프라인 참석 못하더라도 따라오실 자신이 있으신 분들은.. 허용하는 게 어떨까요?

2번
- 기존에는 간식 등의 명목으로 1만원을 받았는데, 이번에는 온라인 위주로 명분이 조금 부족해서..
- 스터디 진행/관리 명분이라면 5천원 정도가 낫지 않을까요??

**Comment by ujuc** [comment]
1. 가능하면 참석 안되면..ㅠ.ㅠ. 온라인 참석.ㅠ.ㅠ.
2. 진행 관리명분으로 5천원 찬성!

**Comment by ghost** [comment]
그럼 일단 5천원으로 정하는걸로 하겠습니다. 
그런데 금주에는 화, 수 이틀 밖에 없어서 이번엔 좀 어렵지않나 싶네요.
이 부분은 의견 공유 한것으로 마무리 하고 다음에 기회가 있으면 이렇게 할까 싶습니다. 

참석은 가능하되, 온라인 으로 결정된것으로 의견이 모아진것으로 보입니다.

그럼 여기는 close하겠습니다.

**Comment by ghost** [comment]
생각해보니 5천원이면 수수료가 10%네요. 
앞으로는 최소 1만원으로 해야 할것같습니다.
