### ISSUE TITLE
6명 이외에 나머지 분들도 다 참여 시킬지 여부 

### ISSUE THREAD

**Issue by ghost** [openstack-kr/community-project-management#3]
현재로서는 자력으로 설치 해본 본 분들이면
스터디에 도움이 될것으로 보여서, 6명 이외에 다른 모든분들도 참여 시키는게 
좋을것 같다는 의견입니다.

**Comment by ianychoi** [comment]
인원 업데이트 (참고용)

총 29명
- 기존 A반: 7명
- 기존 B반: 6명
- 추가 후보 (오픈스택 저장소에 커밋도 해 보았다.): 3
- 추가 후보 (많지 않지만 코드 분석 / 개발에 자신있다.): 4
- 추가 후보 (설치하고 간단한 사용까지 해 보았다.): 9

**Comment by ianychoi** [comment]
일단 모든 인원 분들의 background가 개발쪽이 아닐 수가 있는 만큼 
(기존 분들도 포함)

해당 분들과 어떤 식으로 스터디를 진행할지 좀 더 생각을 한 후 결정해야 할 거 같애서요.

총 29명 모든 분들이 Magnum쪽 SIG에 참여가 가능하련지,
그리고 설치/엔지니어링 그룹 쪽에서 5-7월에는 무엇을 진행할지.. 생각을 해 보고 있는데 
아직 저는 구체화까지 못 한 상태라... ㅎㅎ

규모가 좀 커지는 거 같아 걱정은 조금 있습니다만..... 머 ㅎㅎ

**Comment by ghost** [comment]
채팅에서 논의해서 참여하는 방향으로 결정하였습니다.  그럼 close하겠습니다.
